version: "3.7"
services:
  database:
    restart: always
    container_name: database
    image: postgres:10.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - back-end
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-end

  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    image: portfolio-app
    volumes:
      - .:/portfolio-app
      - static_volume:/portfolio-app/staticfiles/
    depends_on:
      - database
      - redis
    entrypoint: ["/bin/bash", "-c", "/portfolio-app/docker/start_api.sh"]
    stdin_open: true
    tty: true
    networks:
      - back-end
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TO_EMAIL=${TO_EMAIL}

  proxy:
    image: portfolio-nginx
    container_name: proxy
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - back-end
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/portfolio-app/static/
      # - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

networks:
  back-end:
volumes:
  static_volume:
  database_volume:
