# Generated by Django 4.0.3 on 2022-04-08 07:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('filter', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('subject', models.TextField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('url', models.CharField(db_index=True, max_length=500)),
                ('is_small', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('client', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('completion_date', models.DateField(db_index=True, max_length=50)),
                ('tags', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None)),
                ('technologies', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('ongoing', models.BooleanField(default=False)),
                ('url', models.CharField(db_index=True, max_length=250)),
                ('thumbnail_image_url', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('categories', models.ManyToManyField(to='portfolio.category')),
                ('images', models.ManyToManyField(to='portfolio.image')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
    ]
