# Generated by Django 4.0.3 on 2022-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_image_url',
            field=models.URLField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
