# Generated by Django 4.0.3 on 2022-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_image_url_alter_project_thumbnail_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='projects_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='skill_level',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
