# Generated by Django 4.0.3 on 2022-04-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_projects_done_category_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('header_image_url', models.URLField(blank=True, db_index=True, max_length=500, null=True)),
                ('header_message', models.TextField(blank=True, null=True)),
                ('about_message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(db_index=True, max_length=50)),
                ('short_name', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(db_index=True, max_length=500)),
                ('icon_name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Socials',
                'verbose_name_plural': 'Socials',
                'ordering': ['-created_at'],
            },
        ),
    ]
