# Generated by Django 4.0.4 on 2022-04-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_extraimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
    ]
