# Generated by Django 4.0.4 on 2022-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_link',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
