# Generated by Django 4.0.4 on 2022-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_resume_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('left_image_url', models.URLField(max_length=500)),
                ('right_image_url', models.URLField(max_length=500)),
                ('bottom_image_url', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
